### ISSUE TITLE
DCCN-2024: добавить PDF-файл программы на сайт

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#12]
@timac11 
Просьба разместить на странице https://2024.dccn.ru/program файл программы для скачивания (пока только PDF):
[DCCN2024_program.pdf](https://github.com/user-attachments/files/17072784/DCCN2024_program.pdf)

[DCCN2024_program.PDF](https://2024.dccn.ru/downloads/DCCN2024_program.pdf)- full conference program in PDF format (updated on 20.09.2023)

**Comment by timac11** [comment]
done

**Comment by kozyrevdv** [comment]
@timac11 

Сорян, внесли новые правки в программу. Просьба обновить файл:

[DCCN2024_program.pdf](https://github.com/user-attachments/files/17074066/DCCN2024_program.pdf)
