### ISSUE TITLE
DCCN-2024: Link to Join Plenary Session

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#13]
@timac11 
Просьба разместить кнопку на глагне https://2024.dccn.ru/ и ссылку на странице  https://2024.dccn.ru/program для подключения к пленарному заседанию:
[Link to Join Plenary Session](https://telemost.yandex.ru/live/0da2043b039749efa816bb2e33e9d743)

**Comment by timac11** [comment]
done
