### ISSUE TITLE
DCCN-2024: Links to Join Track Sessions

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#14]
@timac11 

Просьба разместить на странице https://2024.dccn.ru/program ссылки на подключение к секционным заседаниям по трекам:

[Link to Join Track A ](https://telemost.yandex.ru/j/95989188497129)

[Link to Join Track B-1](https://telemost.yandex.ru/j/70296155683332)

[Link to Join Track B-2](https://telemost.yandex.ru/j/95989188497129)

[Link to Join Track C](https://telemost.yandex.ru/j/01242678496824)

**Comment by timac11** [comment]
done
