### ISSUE TITLE
DCCN-2024: добавить соавтора в программе

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#16]
@timac11 
Просьба в https://dccn.ru/program#B-2.2 добавить соавтора доклада (Илья Галишников - собственно, он и будет докладываться):

[Дерево отказов для системы гибридного распознавания номеров транспортных средств](https://dccn.ru/papers/3099)
Dmitrii Aminev, Ilya Galishnikov, Dmitry Kozyrev

**Comment by timac11** [comment]
done
