### ISSUE TITLE
DCCN-2024: upload the RSCI proceedings book

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#17]
@timac11 
Просьба загрузить на сервер сборник РИНЦ и разместить на глагне https://2024.dccn.ru/ ссылку для его скачивания.
[Download RSCI Proceedings Volume](https://2024.dccn.ru/downloads/DCCN-2024_proceedings.zip)

Сам сборник лежит на яндекс диске: https://disk.yandex.ru/d/EQocwXCnUnMTcw

**Comment by timac11** [comment]
done
