### ISSUE TITLE
DCCN-2024: добавить текст и логотип LNCS

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#18]
@timac11 просьба внести изменения (отмечены курсивом ниже) в текст на странице https://2024.dccn.ru/#about и добавить логотип LNCS:

The revised selected submissions in English, recommended by the Program Committee, also appear as a stand-alone volume of selected extended papers published by Springer _in the Lecture Notes in Computer Science (LNCS) series_ (indexed in Scopus and Web of Science). _Previous DCCN proceedings are available on [SpringerLink](https://link.springer.com/conference/dccn)._

Архив с логотипом в разных форматах:
[LNCS_Image.zip](https://github.com/user-attachments/files/17431991/LNCS_Image.zip)

**Comment by timac11** [comment]
done
