### ISSUE TITLE
DCCN-2024: Authors

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#4]
@timac11
Просьба открыть раздел https://2024.dccn.ru/authors по образцу прошлого года. 

Изменения:

1. Заменить ссылки на архивы с шаблонами на новые:
[DCCN2024_LaTeX_RU.zip](https://github.com/user-attachments/files/15554223/DCCN2024_LaTeX_RU.zip)
[DCCN2024_LaTeX_EN.zip](https://github.com/user-attachments/files/15554228/DCCN2024_LaTeX_EN.zip)

2. Ссылки на Overleaf пока убрать. Их еще не утвердили... Соответствующую фразу удалить:
_For your convenience, we made available the DCCN templates in the scientific authoring platform Overleaf:_

**Comment by timac11** [comment]
done
