### ISSUE TITLE
DCCN-2024: Authors + Overleaf

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#6]
@timac11 Просьба в разделе https://2024.dccn.ru/authors

Добавить перед "After a peer review.."  нижеследующую фразу и ссылки

 For your convenience, we made available the DCCN templates in the scientific authoring platform Overleaf:
[Overleaf DCCN'2024 Submission Template (RUS)](https://www.overleaf.com/latex/templates/dccn2024-latex-ru/twkvpjwqpbfj)
[Overleaf DCCN'2024 Submission Template (ENG)](https://www.overleaf.com/latex/templates/dccn2024-submission-template-eng/dgycmnndxktc)

**Comment by timac11** [comment]
done
