### ISSUE TITLE
DCCN-2024: keynote speakers

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web24#7]
@timac11
Просьба открыть раздел Keynote Speakers https://2024.dccn.ru/#keynotes
и заполнить его.

Всего 4 пленарных докладчика. Пока есть полные данные о 3:
1.
**Prof. Abdelhamied A. Ateya**, Zagazig University and Prince Sultan University, Riyadh, Saudi Arabia
![Abdelhamied A  Ateya](https://github.com/dccnconf/web24/assets/47321403/c031cf0b-3a4b-4c58-b85b-6b94853db236)

**About the speaker**
Abdelhamied A. Ateya (Senior Member, IEEE, 2021) received the B.Sc. and M.Sc. in Electrical Engineering from Zagazig University, Egypt, in 2010 and 2014, respectively. In 2019, he received the Ph.D. from Saint-Petersburg State University of Telecommunications, Russia. He is currently an Assistant professor at the Electronics and Communications Engineering Department, Faculty of Engineering, Zagazig University, and a Researcher at the EIAS Data Science Lab, College of Computer and Information Sciences, Prince Sultan University, Riyadh, Saudi Arabia. He has co-authored more than 70 publications in high-ranked journals. He is a member of many scientific communities. Dr. Abdelhamied is an IEEE Senior Member and an ACM prof. Member. He has been an active member of several international journals and conferences, with a contribution as an author, a reviewer, an editor, or a member of program committees. His current research interests include machine learning applications in communication networks, 5G/6G communications, Internet of Things, Tactile Internet and its standardization, and Vehicular communications.

Название доклада:  **Emerging Security Solutions for the Internet of Things Networks**

**Abstract**
The rapid evolution of Internet of Things (IoT) networks has completely transformed multiple industries, including healthcare, smart cities, industrial automation, and home automation. However, this growth has been associated with significant security challenges, requiring strong and innovative measures to protect these networked devices. The talk will examine the latest security solutions for IoT networks, specifically focusing on trust management methods. These mechanisms play a critical part in ensuring the security and reliability of data and communications. Trust management for the IoT involves assessing the reliability and security of devices and their interactions, reducing the potential risks posed by malevolent actors and hacked equipment. Some new solutions being developed include trust frameworks based on blockchain technology, algorithms that use machine learning to detect anomalies, and models for evaluating decentralized trust. These approaches seek to improve security by offering scalable, adaptable, and resilient strategies to secure IoT networks from various attacks. The talk will investigate the difficulties in implementing and researching the future of IoT, emphasizing the importance of established protocols to create thorough security methods for the changing IoT environment.

2. **Prof. Abdelkader Laouid**, University of El Oued, Algeria
![Abdelkader-Laouid-2](https://github.com/dccnconf/web24/assets/47321403/e971aada-2ba4-48d4-aee3-5e9b2d4303fb)

**About the speaker**
Prof. Abdelkader Laouid is a distinguished computer science professor and researcher at the University of El Oued, Algeria, where he serves as the Head of the LIAP Artificial Intelligence Laboratory and Director of the Artificial Intelligence House. With a Ph.D. in Computer Science from the University of Béjaïa 2017, Prof. Laouid has significantly contributed to the fields of distributed systems, cybersecurity, and artificial intelligence. He has overseen multiple Ph.D. dissertations and spearheaded several innovative projects, including the development of CupCarbon, a renowned IoT simulator. Prof. Laouid is actively involved in university ranking and research production evaluations, reflecting his commitment to advancing academic and research excellence.

Название доклада: **The Escalating Cybersecurity Threats in the Era of Quantum Computers: Challenges and Solutions**

**Abstract**
The advent of quantum computers poses unprecedented challenges to various fields, particularly cybersecurity. As these powerful machines become a reality, they threaten to undermine the cryptographic systems that form the backbone of our digital security infrastructure. This keynote addresses the escalating cybersecurity threats in the presence of quantum computers, exploring how their immense computational power can break widely used encryption methods, such as RSA and ECC, in a fraction of the time required by classical computers. We will delve into the potential implications for data privacy, secure communications, and critical infrastructure, emphasizing the urgency of developing quantum-resistant cryptographic solutions. Additionally, the keynote will discuss the current progress in post-quantum cryptography, strategies for transitioning to quantum-safe systems, and the collaborative efforts required from governments, academia, and industry to safeguard our digital future in the quantum era.

3. **Prof. Sachin Sharma**, State Bank of India
![Sharma Sachin](https://github.com/dccnconf/web24/assets/47321403/c6a1a8e9-ad8f-40e5-a73f-351b91d2990b)

**About the speaker**
With over 16 years of extensive industry experience in Fortune 500 organizations such as International Business Machines (IBM), Tata Consultancy Services (TCS), and State Bank of India (SBI), Dr. Sachin Sharma brings a wealth of expertise to the table. His diverse background spans sectors such as Telecommunication Technology, Retail, BFSI, and various IT domains. In 2020, Dr. Sharma earned a Ph.D. from Maharishi Markandeshwar University Mullana, demonstrating his commitment to advancing knowledge. His exceptional research contributions secured the prestigious Research Fellowship in Banking Technology for 2021-22, a collaboration between IIBF and IDRBT. Dr. Sharma's research interests encompass cutting-edge domains like Data Analytics, Information Security, Networking, and Biometrics. Additionally, he holds renowned international certifications, including Project Management Professional (PMP), TOGAF 9 Enterprise Architecture Certificate, and Oracle Certified Professional (OCP) DBA, further enhancing his global industry recognition.

Название доклада: **Repeated Line Tracking and Multiline Neighbouring Relation (RLMN) framework for finger vein template security**

**Abstract**
In the era of rapid digitization, password management has become a significant challenge, prompting financial institutions to explore biometric alternatives for user authentication. Biometrics offers seamless and secure authentication, yet poses unique security risks, especially since biometric data cannot be changed if compromised. This keynote presents the Repeated Line Tracking and Multiline Neighbouring Relation (RLMN) framework, a novel approach for enhancing the security of finger vein templates in biometric systems. Emphasizing the importance of cancelability, this framework converts three-dimensional finger vein features into a single binary string, ensuring secure storage and robust authentication. We will explore its application in the banking sector, comparing it with other biometric systems, and discussing its potential to revolutionize identity verification. The session will also cover real-world implementations, such as those by Barclays and FinGo, and outline future research directions to address evolving security challenges in biometrics.

**Comment by kozyrevdv** [comment]
@timac11 

еще четвёртый пленарник подъехал:

4. Prof. Neeraj Kumar, Thapar Institute of Engineering & Technology, India (Full Professor).
![mailservice](https://github.com/dccnconf/web24/assets/47321403/d8f87da9-eedf-4c2b-b9fc-ce95dc9bbcf8)


**About the speaker**
Prof. Neeraj Kumar  (SMIEEE)  (2019, 2020, 2021 highly-cited researcher from WoS) is working as a Full Professor in the Department of Computer Science and Engineering, Thapar Institute of Engineering and Technology (Deemed to be University), Patiala (Pb.), India.  He is also adjunct professor at King Abdul Aziz University, Jeddah, Saudi Arabia and Newcastle University, UK. He has published more than 500 technical research papers in top-cited journals and conferences which are cited more than 54900 times from well-known researchers across the globe with current h-index of 125. He has guided many research scholars leading to Ph.D. and M.E./M.Tech. His research is supported by funding from various competitive agencies across the globe.  His broad research areas are Green computing and Network management, IoT, Big Data Analytics, Deep learning and cyber-security.  He has also edited/authored 10 books with International/National Publishers like IET, Springer, Elsevier, CRC. 
He has secured research funding of around 1 Million Euro from Govt of India, and Industries in the area of smart grid, blockchain, Cyber-Security and network management. He is consultant In various industry and govt. sponsored projects in China, Saudi Arabia and Europe. He has executed various international projects in Austria, Poland, Saudi Arabia, Europe and China. He has supervised more than 15 Ph.D. and 25 M.E./M.Tech. students.

He is serving as editors of ACM Computing Survey, IEEE Transactions on Sustainable Computing, IEEE TNSM,  Elsevier Computer Communication,  Wiley International Journal of Communication Systems. Also, he has organized various special issues of journals of repute from IEEE, Elsevier, Springer.  He has been a workshop chair at IEEE Globecom 2018, IEEE Infocom 2020 and IEEE ICC 2020 and track chair of Security and privacy of IEEE MSN 2020. He is also TPC Chair and member for various International conferences such as IEEE MASS 2020, IEEE MSN2020. He has won the best papers award from IEEE Systems Journal in 2018, in 2020, and IEEE ICC 2018, Kansas-city in 2018. He has also won best paper award from Elsevier JNCA in 2021 and IEEE Comsoc IWCMC 2021. He has won the outstanding leadership award from IEEE Trustcom in 2021. Moreover, He won the best researcher award from parent organization every year from last eight consecutive years.

Название доклада: **Quantum Blockchain for Next Generation Networks Scenarios: Use Cases, Challenges and Future Directions**

**Abstract**: 
Quantum Blockchain is the intersection of quantum computing and blockchain technology, exploring both the challenges posed by quantum computing to existing blockchain systems and the opportunities for innovation in creating more secure and efficient decentralized networks.   However, various challenges such as secure communication, scalability, fast processing, key distribution etc. need to be addressed by designing new innovative solutions.   Quantum computing could potentially enable more efficient consensus mechanisms in blockchain networks, leading to faster transaction confirmations and scalability improvements. It also  offers new cryptographic techniques, such as quantum key distribution (QKD), which could enhance the security and privacy of blockchain transactions. Moreover, Qubit design is challenging keeping in view of the overall performance evaluation of any system.
Hence, in this talk, we will explore various possibilities of application of Quantum blockchain for wide range of applications scenarios for future.

**Comment by timac11** [comment]
добавил

**Comment by kozyrevdv** [comment]
@timac11 
Просьба добавить инфу про еще одного, пятого (и последнего) пленарного докладчика:

5. Prof. Ammar Muthanna, the Bonch-Bruevich Saint Petersburg State University of Telecommunications, Russia (Professor).
![Изображение WhatsApp 2024-08-14 в 17 34 03_683c5075](https://github.com/user-attachments/assets/799e7dd0-011e-47ef-a42b-95a2edca1056)


**About the speaker**
Dr. Ammar Muthanna, a Senior Member of IEEE, received his B.Sc., M.Sc., Ph.D., and Dr.Sc. degrees from the Saint-Petersburg State University of Telecommunications in 2009, 2011, 2016, and 2023, respectively. Dr. Muthanna currently holds a professorship at the Saint-Petersburg State University of Telecommunications. Between 2017 and 2019, he served as a Postdoctoral Researcher, and since 2020, he has directed the Scientific Center for Future Wireless Networks Modeling at RUDN University. Additionally, he participated in the Erasmus Student Program at the Faculty of Electrical Engineering, University of Ljubljana, in 2012 and 2013, and was a Visiting Researcher at Tampere University, Finland, in 2014. He is an IEEE Senior Member and an ACM Professional Member. Dr. Muthanna has actively contributed to numerous international conferences and journals, serving as Chair or Co-Chair for several Scopus-indexed conferences, and as an academic or associate editor for multiple journals indexed in Web of Science (WoS) and Scopus. He also serves as an Editor for draft recommendations in ITU-T SG 11, SG 13, and SG 16, and is an Expert on the Judges Panel and Challenge Management Board at AI-5G-Challenge, ITU. He organized the Russian Host for the AI-5G-Challenge in 2020 and 2021 at Saint-Petersburg State University of Telecommunications. His research interests include wireless communications, 5G/6G cellular systems, artificial intelligence, high-density IoT, telepresence applications, edge/fog computing, and software-defined networking.

Название доклада: **Holographic City - CitiVerse**

**Abstract:**
The Holographic City is an example of a technological and urban design innovation that combines sophisticated holography with digital and physical infrastructures to create immersive and dynamic urban experiences. The holographic projections make it easier to see public services, architecture, and city planning in real time, which improves decision-making and creates a stronger sense of community. In addition, the Holographic City combines holography, virtual reality, and augmented reality to provide innovative uses in travel, education, and entertainment. By using accurate simulations and data-driven insights, this technology's use also promises to increase sustainability and efficiency in urban management. The Holographic City presents an innovative approach to building smarter, more resilient, and interesting urban environments as cities confront escalating issues with regard to resource management, population expansion, and environmental impact. 
A creative way to make cities more intelligent, robust, and interesting is provided by The Holographic City. In this presentation, the term "holographic city" refers to the cross-sectoral integration of the metaverse into urban settings, wherein digital and tangible items interact with the local digital ecosystem.  This presentation aims to showcase actual instances of metaverse technology implementation in various urban settings. Particular emphasis will be placed on instances where cities prioritize the requirements of their citizens in all services provided within their holographic city models.
